# Kafka Configuration
kafka.bootstrap.servers=nakupify-kafka-kafka-bootstrap.default.svc.cluster.local:9092

# words
mp.messaging.incoming.words-in.auto.offset.reset=earliest
mp.messaging.incoming.words-in.topic=words
mp.messaging.incoming.words-in.connector=smallrye-kafka
mp.messaging.outgoing.words-out.topic=words
mp.messaging.outgoing.words-out.connector=smallrye-kafka

# PostgreSQL Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=nakupify
quarkus.datasource.password=nakupify
quarkus.datasource.jdbc.url=jdbc:postgresql://nakupify-db-rw.default.svc.cluster.local:5432/nakupify
quarkus.datasource.health.enabled=true
quarkus.hibernate-orm.database.generation=drop-and-create

# Health check path
#quarkus.smallrye-health.root-path=/izdelki/health

# GraphQL
quarkus.smallrye-graphql.ui.always-include=true
#quarkus.smallrye-graphql.path=/izdelki/graphql
#quarkus.smallrye-graphql.playground.path=/izdelki/graphql-playground

# OpenAPI Info
quarkus.smallrye-openapi.info-title=Katalog izdelkov
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Mikrostoritev za upravljanje izdelkov.
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

# Swagger UI
quarkus.swagger-ui.always-include=true
#quarkus.swagger-ui.path=/izdelki/swagger-ui
#quarkus.swagger-ui.url=/izdelki/openapi

